// lib/upgrades.ts
export interface Buildings {
  id: string;
  name: string;
  type: 'sustainable' | 'industrial';
  baseCost: number;
  energy: number;
  costMultiplier?: number;
  pollution: number;
  pollutionReduction?: number;
  addPollutionLimit?: number;
}

const defaultIndustrialMultiplier = 1.15;
const defaultEcoMultiplier = 1.2;

export const industrialBuildings: Buildings[] = [
  {
    id: 'coal-power-plant',
    name: 'Coal Power Plant',
    type: 'industrial',
    baseCost: 10,
    energy: 0.2,
    costMultiplier: defaultIndustrialMultiplier,
    pollution: 0.5,
  },
  {
    id: 'natural-gas-plant',
    name: 'Natural Gas Plant',
    type: 'industrial',
    baseCost: 80,
    energy: 0.4,
    costMultiplier: defaultIndustrialMultiplier,
    pollution: 0.2,
  },
  {
    id: 'oil-fired-plant',
    name: 'Oil-Fired Plant',
    type: 'industrial',
    baseCost: 400,
    energy: 0.8,
    costMultiplier: defaultIndustrialMultiplier,
    pollution: 0.6,
  },
  {
    id: 'diesel-generator-building',
    name: 'Diesel Generator Building',
    type: 'industrial',
    baseCost: 650,
    energy: 1.5,
    costMultiplier: defaultIndustrialMultiplier,
    pollution: 0.8,
  },
  {
    id: 'incinerator',
    name: 'Incinerator',
    type: 'industrial',
    baseCost: 800,
    energy: 1,
    costMultiplier: defaultIndustrialMultiplier,
    pollution: 1.5,
  },
  {
    id: 'coal-liquefaction-plant',
    name: 'Coal Liquefaction Plant',
    type: 'industrial',
    baseCost: 1000,
    energy: 1.8,
    costMultiplier: defaultIndustrialMultiplier,
    pollution: 1.5,
  },
  {
    id: 'petrochemical-plant',
    name: 'Petrochemical Plant',
    type: 'industrial',
    baseCost: 1500,
    energy: 2,
    costMultiplier: defaultIndustrialMultiplier,
    pollution: 2.2,
  },
  {
    id: 'offshore-oil-harvester',
    name: 'Offshore Oil Harvester',
    type: 'industrial',
    baseCost: 2000,
    energy: 2.5,
    costMultiplier: defaultIndustrialMultiplier,
    pollution: 3,
  },
  {
    id: 'synthetic-natural-gas-plant',
    name: 'Synthetic natural gas (SNG) Plant',
    type: 'industrial',
    baseCost: 2500,
    energy: 2.8,
    costMultiplier: defaultIndustrialMultiplier,
    pollution: 4,
  },
  {
    id: 'carbon-capture-and-storage-facility',
    name: 'Carbon Capture and Storage (CCS) Facility',
    type: 'industrial',
    baseCost: 3000,
    energy: 0,
    costMultiplier: defaultIndustrialMultiplier,
    pollution: 4,
    pollutionReduction: 10,
    addPollutionLimit: 5000,
  },
];

export const ecoBuildings: Buildings[] = [
  {
    id: 'solar-farm',
    name: 'Solar Farm',
    type: 'sustainable',
    baseCost: 50,
    energy: 0.1,
    costMultiplier: defaultEcoMultiplier,
    pollution: 0,
    pollutionReduction: 0.1,
  },
  {
    id: 'wind-turbine',
    name: 'Wind Turbine',
    type: 'sustainable',
    baseCost: 100,
    energy: 0.2,
    costMultiplier: defaultEcoMultiplier,
    pollution: 0,
    pollutionReduction: 0.2,
  },
  {
    id: 'green-roof-buildings',
    name: 'Green Roof Buildings',
    type: 'sustainable',
    baseCost: 300,
    energy: 0,
    costMultiplier: defaultEcoMultiplier,
    pollution: 0,
    pollutionReduction: 0.2,
    addPollutionLimit: 500,
  },
  {
    id: 'community-solar-garden',
    name: 'Community Solar garden',
    type: 'sustainable',
    baseCost: 500,
    energy: 0.3,
    costMultiplier: defaultEcoMultiplier,
    pollution: 0,
    pollutionReduction: 0.5,
  },
  {
    id: 'living-wall',
    name: 'Living Wall',
    type: 'sustainable',
    baseCost: 500,
    energy: 0,
    costMultiplier: defaultEcoMultiplier,
    pollution: 0,
    pollutionReduction: 0.5,
    addPollutionLimit: 1000,
  },
  {
    id: 'hydroelectric-plant',
    name: 'Hydroelectric Plant',
    type: 'sustainable',
    baseCost: 900,
    energy: 0.5,
    costMultiplier: defaultEcoMultiplier,
    pollution: 0,
    pollutionReduction: 0,
  },
  {
    id: 'vertical-farming',
    name: 'Vertical Farming',
    type: 'sustainable',
    baseCost: 1000,
    energy: 0,
    costMultiplier: defaultEcoMultiplier,
    pollution: 0,
    pollutionReduction: 1,
    addPollutionLimit: 2000,
  },
  {
    id: 'geothermal-plant',
    name: 'Geothermal Plant',
    type: 'sustainable',
    baseCost: 1500,
    energy: 1,
    costMultiplier: defaultEcoMultiplier,
    pollution: 0,
    pollutionReduction: 1.5,
  },
  {
    id: 'biomass-facility',
    name: 'Biomass Facility',
    type: 'sustainable',
    baseCost: 2500,
    energy: 1.5,
    costMultiplier: defaultEcoMultiplier,
    pollution: 0,
    pollutionReduction: 1,
  },
  {
    id: 'reforestation-project',
    name: 'Reforestation Project',
    type: 'sustainable',
    baseCost: 3000,
    energy: 0,
    costMultiplier: defaultEcoMultiplier,
    pollution: 0,
    pollutionReduction: 0.5,
    addPollutionLimit: 5000,
  },
];
